name: CI - SonarCloud (Python)

on:
  push:
    branches: ['**']          # dispara en cualquier rama
  pull_request:
    branches: ['**']
  workflow_dispatch:           # permite correrlo manualmente

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # pull-requests: write   # solo si quieres decoración en PRs

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # SonarCloud usa historia para algunas features

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install pytest pytest-cov

      - name: Run tests with coverage (XML)
        run: |
          pytest -q --disable-warnings --maxfail=1 \
            --cov=src --cov-branch \
            --cov-report=xml:coverage.xml
          test -f coverage.xml || (echo "NO coverage.xml"; exit 1)

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # opcional para PRs
        with:
          args: >
            -Dsonar.projectKey=sebastianforero1_corregido_refactor
            -Dsonar.organization=sebastianforero1
            -Dsonar.python.version=3.11
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/__pycache__/**,**/*.pyc
